#!/usr/bin/env python3
"""
Initialize a vibeflow project structure.

Creates the deterministic scaffold artifacts needed for multi-session agent work:
- feature-list.json (empty template with tech_stack, quality_gates, required_configs)
- task-progress.md (empty progress log)
- RELEASE_NOTES.md (living release notes, Keep a Changelog format)
- CLAUDE.md (appended with vibeflow reference for cross-session continuity)
- examples/ directory with README.md (runnable examples for completed features)
- scripts/ directory (for validate_features.py, check_configs.py, check_devtools.py)
- docs/plans/ directory (for design docs and implementation plans)

NOTE: The following files are NOT generated by this script — they are created by the
LLM during the Initializer phase, tailored to the project's specific tech stack:
- vibeflow-guide.md (Worker session guide — LLM generates from SKILL.md + references)
- init.sh / init.ps1 (environment bootstrap — LLM generates from design doc)

Feature schema supports optional UI fields:
- "ui": true/false — marks features that require Chrome DevTools MCP functional testing
- "ui_entry": "/path" — entry URL for the UI feature (used by Worker for navigate_page)
- UI features must have at least one verification_step prefixed with "[devtools]"

Usage:
    python scripts/init_project.py <project-name> [--path <output-dir>]
           [--lang <language>] [--test-framework <framework>]
           [--coverage-tool <tool>] [--mutation-tool <tool>]
           [--line-cov <0-100>] [--branch-cov <0-100>] [--mutation-score <0-100>]
"""

import argparse
import json
import os
import shutil
import sys
from datetime import datetime


CLAUDE_MD_MARKER = "<!-- vibeflow -->"

_VIBEFLOW_REFERENCE_BODY = (
    "\n\n<!-- vibeflow -->\n"
    "## VibeFlow\n\n"
    "This project uses a multi-session agent workflow.\n"
    "Flow: Think → Plan Review → Requirements (SRS) → UCD → Design → Build Init → Build Work → Review → Test System → QA → Ship → Reflect.\n\n"
    "Incremental development: `increment-request.json` triggers the Increment skill which updates SRS/Design/UCD in place, new features are appended, Worker cycles run, then ST.\n\n"
    "Key files: `docs/plans/*-srs.md` (SRS), `docs/plans/*-ucd.md` (UCD), "
    "`docs/plans/*-design.md` (design), "
    "`feature-list.json` (task inventory), "
    "`task-progress.md` (session log), "
    "`RELEASE_NOTES.md` (changelog), "
    "`docs/test-cases/feature-*.md` (per-feature ST test cases), "
    "`increment-request.json` (increment signal).\n"
    "<!-- /vibeflow -->\n"
)

CLAUDE_MD_REFERENCE = _VIBEFLOW_REFERENCE_BODY


def _append_agent_md_reference(out_dir: str, project_name: str, filename: str):
    """Append vibeflow reference to an agent instruction file (idempotent)."""
    path = os.path.join(out_dir, filename)

    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        if CLAUDE_MD_MARKER in content:
            print(f"Skipped: {path} (reference already exists)")
            return
        with open(path, "a", encoding="utf-8") as f:
            f.write(_VIBEFLOW_REFERENCE_BODY)
        print(f"Updated: {path} (appended vibeflow reference)")
    else:
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"# {project_name}\n")
            f.write(_VIBEFLOW_REFERENCE_BODY)
        print(f"Created: {path}")


def append_claude_md_reference(out_dir: str, project_name: str):
    """Append vibeflow reference to CLAUDE.md (idempotent)."""
    _append_agent_md_reference(out_dir, project_name, "CLAUDE.md")



def create_feature_list(
    project_name: str,
    language: str = "TODO",
    test_framework: str = "TODO",
    coverage_tool: str = "TODO",
    mutation_tool: str = "TODO",
    line_coverage_min: int = 90,
    branch_coverage_min: int = 80,
    mutation_score_min: int = 80,
) -> dict:
    return {
        "project": project_name,
        "created": datetime.now().strftime("%Y-%m-%d"),
        "tech_stack": {
            "language": language,
            "test_framework": test_framework,
            "coverage_tool": coverage_tool,
            "mutation_tool": mutation_tool
        },
        "quality_gates": {
            "line_coverage_min": line_coverage_min,
            "branch_coverage_min": branch_coverage_min,
            "mutation_score_min": mutation_score_min
        },
        "constraints": [],
        "assumptions": [],
        "required_configs": [],
        "features": []
    }


# Preset tool mappings per language
LANG_PRESETS = {
    "python": {
        "test_framework": "pytest",
        "coverage_tool": "pytest-cov",
        "mutation_tool": "mutmut",
    },
    "java": {
        "test_framework": "junit",
        "coverage_tool": "jacoco",
        "mutation_tool": "pitest",
    },
    "javascript": {
        "test_framework": "jest",
        "coverage_tool": "c8-jest",
        "mutation_tool": "stryker",
    },
    "typescript": {
        "test_framework": "vitest",
        "coverage_tool": "c8",
        "mutation_tool": "stryker",
    },
    "c": {
        "test_framework": "ctest",
        "coverage_tool": "gcov",
        "mutation_tool": "mull",
    },
    "cpp": {
        "test_framework": "gtest",
        "coverage_tool": "gcov",
        "mutation_tool": "mull",
    },
    "c++": {
        "test_framework": "gtest",
        "coverage_tool": "gcov",
        "mutation_tool": "mull",
    },
}


def create_progress_log(project_name: str) -> str:
    return f"""# Task Progress — {project_name}

## Current State
Progress: 0/0 · Last: — · Next: —

---

## Session Log

"""


def create_release_notes(project_name: str) -> str:
    return f"""# Release Notes — {project_name}

## [Unreleased]

### Added
- Initial project scaffold

### Changed
- (none yet)

### Fixed
- (none yet)

---

_Format: [Keep a Changelog](https://keepachangelog.com/) — Updated after every git commit._
"""


def create_examples_readme(project_name: str) -> str:
    return f"""# {project_name} — Examples

Runnable examples demonstrating completed features. Each example corresponds to a feature in `feature-list.json`.

## Index

| # | Feature | File | How to run |
|---|---------|------|------------|
| — | *(examples will be added as features are completed)* | — | — |

---

_Add a new row to this table each time you create an example for a completed feature._
"""



def main():
    parser = argparse.ArgumentParser(description="Initialize a vibeflow project")
    parser.add_argument("project_name", help="Name of the project")
    parser.add_argument("--path", default=".", help="Output directory (default: current dir)")

    # Tech stack options
    parser.add_argument("--lang", default=None,
                        help="Project language (python/java/javascript/typescript/c/cpp). Auto-fills tool defaults.")
    parser.add_argument("--test-framework", default=None,
                        help="Test framework (e.g., pytest, junit, vitest, gtest)")
    parser.add_argument("--coverage-tool", default=None,
                        help="Coverage tool (e.g., pytest-cov, jacoco, c8, gcov)")
    parser.add_argument("--mutation-tool", default=None,
                        help="Mutation tool (e.g., mutmut, pitest, stryker, mull)")

    # Quality gate thresholds
    parser.add_argument("--line-cov", type=int, default=90,
                        help="Min line coverage %% (default: 90)")
    parser.add_argument("--branch-cov", type=int, default=80,
                        help="Min branch coverage %% (default: 80)")
    parser.add_argument("--mutation-score", type=int, default=80,
                        help="Min mutation score %% (default: 80)")

    args = parser.parse_args()

    out_dir = os.path.abspath(args.path)
    os.makedirs(out_dir, exist_ok=True)

    # Resolve tech stack from --lang preset, then override with explicit flags
    language = args.lang or "TODO"
    preset = LANG_PRESETS.get(language.lower(), {}) if language != "TODO" else {}
    test_framework = args.test_framework or preset.get("test_framework", "TODO")
    coverage_tool = args.coverage_tool or preset.get("coverage_tool", "TODO")
    mutation_tool = args.mutation_tool or preset.get("mutation_tool", "TODO")

    # feature-list.json
    fl_path = os.path.join(out_dir, "feature-list.json")
    with open(fl_path, "w", encoding="utf-8") as f:
        json.dump(create_feature_list(
            args.project_name,
            language=language,
            test_framework=test_framework,
            coverage_tool=coverage_tool,
            mutation_tool=mutation_tool,
            line_coverage_min=args.line_cov,
            branch_coverage_min=args.branch_cov,
            mutation_score_min=args.mutation_score,
        ), f, indent=2, ensure_ascii=False)
    print(f"Created: {fl_path}")

    # CLAUDE.md (append reference, never overwrite)
    append_claude_md_reference(out_dir, args.project_name)

    # task-progress.md
    tp_path = os.path.join(out_dir, "task-progress.md")
    with open(tp_path, "w", encoding="utf-8") as f:
        f.write(create_progress_log(args.project_name))
    print(f"Created: {tp_path}")

    # RELEASE_NOTES.md
    rn_path = os.path.join(out_dir, "RELEASE_NOTES.md")
    with open(rn_path, "w", encoding="utf-8") as f:
        f.write(create_release_notes(args.project_name))
    print(f"Created: {rn_path}")

    # scripts dir + copy helper scripts
    scripts_dir = os.path.join(out_dir, "scripts")
    os.makedirs(scripts_dir, exist_ok=True)

    # Resolve plugin root.
    # Two layouts are supported:
    #
    # Layout A — normal checkout (THIS layout):
    #   <repo-root>/scripts/init_project.py
    #   <repo-root>/skills/
    #   => _THIS_DIR = <repo-root>/scripts, _PLUGIN_ROOT = parent of scripts/ = repo root
    #
    # Layout B — hook-copied to target project:
    #   <target-project>/scripts/init_project.py
    #   <target-project>/.vibeflow-plugin-root (hint file written by the hook)
    #   => use the hint file to find the original plugin root
    #
    _THIS_DIR = os.path.dirname(os.path.abspath(__file__))

    # Try Layout A first: _THIS_DIR/../skills/ should exist at repo root
    _candidates = [
        os.path.dirname(_THIS_DIR),  # one level up (Layout A)
        os.path.join(os.path.dirname(_THIS_DIR), 'skills'),  # explicit skills/ path check
    ]
    _repo_root = os.path.dirname(_THIS_DIR)
    if os.path.isdir(os.path.join(_repo_root, 'skills')):
        # Layout A: normal checkout
        _PLUGIN_ROOT = _repo_root
    else:
        # Layout B: hook-copied, use hint file
        _hint_file = os.path.join(_THIS_DIR, '.vibeflow-plugin-root')
        if os.path.isfile(_hint_file):
            with open(_hint_file, encoding='utf-8') as _hf:
                _hint = _hf.read().strip()
            if sys.platform == 'win32' and _hint:
                import re as _re
                _m = _re.match(r'^/?([a-zA-Z])/(.*)', _hint)
                if _m:
                    _hint = _m.group(1).upper() + ':/' + _m.group(2)
            _PLUGIN_ROOT = _hint if (_hint and os.path.isdir(_hint)) else _repo_root
        else:
            _PLUGIN_ROOT = _repo_root
    plugin_scripts_dir = os.path.join(_PLUGIN_ROOT, "scripts")

    helper_scripts = [
        "validate_features.py",
        "check_configs.py",
        "check_devtools.py",
        "validate_guide.py",
        "get_tool_commands.py",
        "validate_st_cases.py",
        "validate_increment_request.py",
        "check_st_readiness.py",
        "new-vibeflow-work-config.py",
    ]
    for script_name in helper_scripts:
        src = os.path.join(plugin_scripts_dir, script_name)
        dst = os.path.join(scripts_dir, script_name)
        if os.path.exists(src) and os.path.abspath(src) != os.path.abspath(dst):
            shutil.copy2(src, dst)
            print(f"Copied: {script_name} -> {scripts_dir}")
        elif not os.path.exists(src):
            print(f"Warning: {script_name} not found in {plugin_scripts_dir}")

    # docs/plans dir
    plans_dir = os.path.join(out_dir, "docs", "plans")
    os.makedirs(plans_dir, exist_ok=True)

    # docs/test-cases dir
    test_cases_dir = os.path.join(out_dir, "docs", "test-cases")
    os.makedirs(test_cases_dir, exist_ok=True)
    print(f"Created: {test_cases_dir}")

    # docs/templates dir — copy ST case template
    templates_dir = os.path.join(out_dir, "docs", "templates")
    os.makedirs(templates_dir, exist_ok=True)
    plugin_templates_dir = os.path.join(_PLUGIN_ROOT, "docs", "templates")
    st_template_src = os.path.join(plugin_templates_dir, "st-case-template.md")
    st_template_dst = os.path.join(templates_dir, "st-case-template.md")
    if os.path.exists(st_template_src) and os.path.abspath(st_template_src) != os.path.abspath(st_template_dst):
        shutil.copy2(st_template_src, st_template_dst)
        print(f"Copied: st-case-template.md -> {templates_dir}")

    # examples dir + README.md
    examples_dir = os.path.join(out_dir, "examples")
    os.makedirs(examples_dir, exist_ok=True)
    examples_readme = os.path.join(examples_dir, "README.md")
    with open(examples_readme, "w", encoding="utf-8") as f:
        f.write(create_examples_readme(args.project_name))
    print(f"Created: {examples_readme}")

    print(f"\nProject '{args.project_name}' initialized at {out_dir}")
    print("Created: feature-list.json, CLAUDE.md, task-progress.md, RELEASE_NOTES.md, examples/, scripts/ (with helper scripts), docs/plans/, docs/test-cases/, docs/templates/")
    print("TODO (LLM generates during Initializer phase):")
    print("  - vibeflow-guide.md          (tailored Worker guide from SKILL.md + references + design doc)")
    print("  - init.sh / init.ps1         (environment bootstrap from design doc tech stack)")


if __name__ == "__main__":
    main()
